### ISSUE TITLE
Can't make it work

### ISSUE THREAD

**Issue by wizkhas** [nwestfall/Xamarin.HotSpotManager#2]
Hey i m currently tryng to configure devices wifi access point with your lib but can't make it work.
I'm on android 8.0.0 and have already given all wifi and network authorisation to the app.
If you have any suggestion, thx !

**Comment by sepp89117** [comment]
Hi,
I also tried to use the library. Unfortunately, it is not possible to provide an AP from Android 8.0 without superuser rights. In Oreo hot-spotting/tethering moved to ConnectionManager, and its annotated @SystemApi, so (nominally) inaccessible.
